// Generated by BUCKLESCRIPT VERSION 1.0.3 , PLEASE EDIT WITH CARE
'use strict';

var $            = require("jquery");
var Jquery$prime = require("jquery");
var $$String     = require("bs-platform/lib/js/string");
var Js_types     = require("bs-platform/lib/js/js_types");

function jquery(prim) {
  return $.jquery(prim);
}

var jquery_ = $.jquery;

function jquery$prime(prim) {
  return Jquery$prime(prim);
}

function addClass(at, jq) {
  if (at[0] >= 5744817) {
    return jq.addClass(at[1]);
  }
  else {
    return jq.addClass(at[1]);
  }
}

function attr_get(prim, prim$1) {
  return prim$1.attr(prim);
}

function attr(at, jq) {
  var variant = at[0];
  if (variant !== 23979) {
    if (variant >= 5442204) {
      return jq.attr(at[1]);
    }
    else {
      return jq.attr(at[1]);
    }
  }
  else {
    var match = at[1];
    return jq.attr(match[0], match[1]);
  }
}

function hasClass(prim, prim$1) {
  return prim$1.hasClass(prim);
}

function html_get(prim) {
  return prim.html();
}

function html(at, jq) {
  if (at[0] >= 5744817) {
    return jq.html(at[1]);
  }
  else {
    return jq.html(at[1]);
  }
}

function prop_get(k) {
  var p = function (param) {
    return param.prop(k);
  };
  var match = Js_types.reify_type(p);
  var v = match[1];
  var switcher = match[0] - 2 | 0;
  if (switcher > 2 || switcher < 0) {
    return /* error */-215364664;
  }
  else {
    switch (switcher) {
      case 0 : 
          return /* `bool */[
                  -1055161302,
                  v
                ];
      case 1 : 
          return /* error */-215364664;
      case 2 : 
          return /* `str */[
                  5744817,
                  v
                ];
      
    }
  }
}

function prop(at, jq) {
  var variant = at[0];
  if (variant !== 23979) {
    if (variant >= 5442204) {
      return jq.prop(at[1]);
    }
    else {
      return jq.prop(at[1]);
    }
  }
  else {
    var match = at[1];
    return jq.prop(match[0], match[1]);
  }
}

function removeAttr(prim, prim$1) {
  return prim$1.removeAttr(prim);
}

function removeClass(at, jq) {
  if (typeof at === "number") {
    return jq.removeClass();
  }
  else if (at[0] >= 5744817) {
    return jq.removeClass(at[1]);
  }
  else {
    return jq.removeClass(at[1]);
  }
}

function removeProp(prim, prim$1) {
  return prim$1.removeProp(prim);
}

function to_js_bool(b) {
  if (b) {
    return true;
  }
  else {
    return false;
  }
}

function toggleClass(at, jq) {
  var variant = at[0];
  if (variant >= -866389342) {
    if (variant >= 5744817) {
      if (variant >= 288862789) {
        var match = at[1];
        return jq.toggleClass($$String.concat(" ", match[0]), match[1] ? true : false);
      }
      else {
        return jq.toggleClass(at[1]);
      }
    }
    else if (variant >= -280389785) {
      var match$1 = at[1];
      return jq.toggleClass(match$1[0], match$1[1]);
    }
    else {
      return jq.toggleClass($$String.concat(" ", at[1]));
    }
  }
  else if (variant >= -866389359) {
    var match$2 = at[1];
    return jq.toggleClass(match$2[0], match$2[1] ? true : false);
  }
  else {
    return jq.toggleClass(at[1]);
  }
}

function val_get(prim) {
  return prim.val();
}

function val_(at, jq) {
  if (at[0] >= 5744817) {
    return jq.val(at[1]);
  }
  else {
    return jq.val(at[1]);
  }
}

function css(prim, prim$1, prim$2) {
  return prim$2.css(prim, prim$1);
}

function outerHeight(prim, prim$1) {
  return prim$1.outerHeight(prim);
}

exports.jquery_      = jquery_;
exports.jquery$prime = jquery$prime;
exports.addClass     = addClass;
exports.attr_get     = attr_get;
exports.attr         = attr;
exports.hasClass     = hasClass;
exports.html_get     = html_get;
exports.html         = html;
exports.prop_get     = prop_get;
exports.prop         = prop;
exports.removeAttr   = removeAttr;
exports.removeClass  = removeClass;
exports.removeProp   = removeProp;
exports.to_js_bool   = to_js_bool;
exports.toggleClass  = toggleClass;
exports.val_get      = val_get;
exports.val_         = val_;
exports.jquery       = jquery;
exports.css          = css;
exports.outerHeight  = outerHeight;
/* jquery_ Not a pure module */
