// Generated by BUCKLESCRIPT VERSION 1.0.3 , PLEASE EDIT WITH CARE
'use strict';

var Jquery = require("./jquery");

function testAttributes() {
  var el = Jquery.jquery("#container");
  el.addClass("test");
  el.addClass(function (_, s) {
        return s + "-list";
      });
  return /* () */0;
}

testAttributes(/* () */0);

exports.testAttributes = testAttributes;
/*  Not a pure module */
