// Generated by BUCKLESCRIPT VERSION 1.0.3 , PLEASE EDIT WITH CARE
'use strict';

var Block  = require("bs-platform/lib/js/block");
var Jquery = require("./jquery");

function attributes_raw() {
  var el = Jquery.jquery("#container");
  el.addClass("test");
  el.addClass(function (_, s) {
        return s + "-list";
      });
  return /* () */0;
}

function attributes_overloaded() {
  var el = Jquery.jquery("#container");
  Jquery.attr(/* Str */Block.__(0, [
          "class",
          "foo"
        ]), el);
  return /* () */0;
}

attributes_raw(/* () */0);

attributes_overloaded(/* () */0);

exports.attributes_raw        = attributes_raw;
exports.attributes_overloaded = attributes_overloaded;
/*  Not a pure module */
